#!/bin/bash

# Parse relevant fields from data.json using jq
name=$(jq -r '.name' data.json | sed 's/.*/\u&/') # Capitalize first letter
formatted_height=$(jq '.height' data.json | awk '{print $1 / 10}') # Convert to meters
formatted_weight=$(jq '.weight' data.json | awk '{print $1 /10}') # Convert to kg
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/') # Capitalize

# Output the formatted string
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
